name: test variables workflow
on:
  workflow_dispatch
env:
  SOMEVAR: Test
jobs:
  initialize_variable:
    runs-on: ubuntu-latest
    steps:
      - name: setvar
        run: echo "SOMEVAR=hello" >> $GITHUB_ENV	
      - name: usevar
        run: echo "var is ${{ env.SOMEVAR }}"	
  use_variable:
    runs-on: ubuntu-latest
    needs: initialize_variable
    steps:
<<<<<<< HEAD
      - name: useenvvar
        run: echo "var is ${{ env.SOMEVAR }}"
=======
      - name: usevar
        run: echo "var is ${{ env.SOMEVAR }}"
>>>>>>> efcc06794154347afc49d8e3ff1f658e756d89f8
